# 42 Inception docker-compose configuration
version: "3.7" #optional, can be changed depends

volumes:
  mariadb:
  wordpress:
  
networks:
  inception:
    name: inception

services:
  mariadb:
    build:
    ports:
    networks:
      - inception
    volumes:
      - "/home/fech-cha/data:/var/lib/mysql"
    restart: "on-failure"
    container_name: "mariadb"
  wordpress:
    build:
    ports:
    networks:
      - inception
    volumes:
      - "/home/fech-cha/data:/var/www/html"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "wordpress"
  nginx:
    build:
    ports:
    networks:
      - inception
    restart: "on-failure"
    depends_on:
      - wordpress
    container_name: "nginx"


