# 42 Inception docker-compose configuration
version: "3.7" #optional, can be changed depends

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/fech-cha/data
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/fech-cha/data
      o: bind
      type: none
  
networks:
  inception:
    name: inception

services:
  mariadb:
    build: ./requirements/mariadb
    ports:
    networks:
      - inception
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "on-failure"
    container_name: "mariadb"
  wordpress:
    build: ./requirements/wordpress
    ports:
    networks:
      - inception
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "wordpress"
  nginx:
    build: ./requirements/nginx
    ports:
    networks:
      - inception
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - wordpress
    container_name: "nginx"


