# 42 Inception docker-compose configuration
version: "3" #optional, can be changed depends
services:
  mariadb:
    build:
    ports:
    networks:
      - inception
    volumes:
    restart: "on-failure"
    container_name: "mariadb"
  wordpress:
    build:
    ports:
    networks:
      - inception
    volumes:
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "wordpress"
  nginx:
    build:
    ports:
    networks:
      - inception
    restart: "on-failure"
    depends_on:
      - wordpress
    container_name: "nginx"

    
volumes:
networks:
  inception:
    name: inception