# 42 Inception docker-compose configuration
version: "3" #optional, can be changed depends
services:
  mariadb:
    build:
    ports:
    networks:
      - inception
    volumes:
    restart: "on-failure"
  wordpress:
    build:
    ports:
    networks:
      - inception
    volumes:
    restart: "on-failure"
    depends_on:
      - mariadb
  nginx:
    build:
    ports:
    networks:
      - inception
    restart: "on-failure"
    depends_on:
      - wordpress
volumes:
networks:
  inception:
    name: inception